---
prometheus_version: 2.52.0
prometheus_port: 9090

# We'll scrape Node Exporter and all our microservices by container name on the Docker network:
prometheus_scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'microservices'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'service-a:80'
          - 'service-b:80'
