---
node_exporter_version: 1.6.1
node_exporter_port: 9100
node_exporter_binary_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_unpacked_dir: node_exporter-{{ node_exporter_version }}.linux-amd64
