---
# Kubernetes namespace to hold all monitoring components
k8s_namespace: monitoring

# Docker images you built earlier
node_exporter_image: custom_node_exporter:latest
prometheus_image:   custom_prometheus:latest
grafana_image:      custom_grafana:latest

# Ports inside the cluster
node_exporter_port: 9100
prometheus_port:    9090
grafana_port:       3000

# Prometheus scrape config (we’ll mount this via a ConfigMap)
prometheus_scrape_configs: |
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'node_exporter'
      static_configs:
        - targets: ['localhost:9100']
    - job_name: 'microservices'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['service-a:80','service-b:80']
