apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  containers:
  - name: master
    image: ansible-node
    imagePullPolicy: Never
    ports:
    - containerPort: 22
---
apiVersion: v1
kind: Pod
metadata:
  name: node1
spec:
  containers:
  - name: node1
    image: ansible-node
    imagePullPolicy: Never
    ports:
    - containerPort: 22
---
apiVersion: v1
kind: Pod
metadata:
  name: node2
spec:
  containers:
  - name: node2
    image: ansible-node
    imagePullPolicy: Never
    ports:
    - containerPort: 22
