apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ssh
  labels:
    app: ssh-target
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "--"]
      args: ["apt update && apt install -y openssh-server && service ssh start && sleep infinity"]
      ports:
        - containerPort: 22
      securityContext:
        privileged: true
